<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1" style="color: black">&copy; 2022 Пожаров Виктор - WebTest</p>
    <ul class="list-inline">
        <li class="list-inline-item"><a href="#" style="color: black">Отзывы</a></li>
        <li class="list-inline-item"><a href="#" style="color: black">О приложении</a></li>
        <li class="list-inline-item"><a href="#" style="color: black">Контакты</a></li>
    </ul>
</footer>